# Configuración de Pub/Sub Topics y Subscriptions
# Para la nueva arquitectura: Cloud Function → Pub/Sub → Image Processing → Email

topics:
  # Topic principal que recibe mensajes del division_service (Cloud Function)
  - name: "shipment-packages-ready"
    description: "Recibe notificaciones cuando los paquetes están listos para procesamiento de imágenes"
    labels:
      environment: "production"
      service: "image-processing"
      version: "2-0"
  
  # Topic para notificaciones de email
  - name: "email-notifications"
    description: "Envía notificaciones de email tras completar el procesamiento"
    labels:
      environment: "production"
      service: "email-service"
      version: "2-0"
  
  # Topic para errores y monitoreo
  - name: "processing-errors"
    description: "Centraliza errores de procesamiento para monitoreo y alertas"
    labels:
      environment: "production"
      service: "monitoring"
      version: "2-0"

subscriptions:
  # Subscription para image processing service
  - name: "image-processing-subscription"
    topic: "shipment-packages-ready"
    push_endpoint: "https://image-processing-service-PROJECT_ID.REGION.run.app/process-pubsub"
    ack_deadline: 600  # 10 minutos para procesar imágenes
    message_retention: 604800  # 7 días
    retry_policy:
      minimum_backoff: "10s"
      maximum_backoff: "600s"
    dead_letter_policy:
      dead_letter_topic: "processing-errors"
      max_delivery_attempts: 5
    labels:
      service: "image-processing"
      type: "push"
  
  # Subscription para email service  
  - name: "email-notifications-subscription"
    topic: "email-notifications"
    push_endpoint: "https://email-service-PROJECT_ID.REGION.run.app/send-pubsub-email"
    ack_deadline: 120  # 2 minutos para enviar email
    message_retention: 86400  # 1 día
    retry_policy:
      minimum_backoff: "5s"
      maximum_backoff: "60s"
    labels:
      service: "email-service"
      type: "push"
  
  # Subscription para monitoreo de errores
  - name: "error-monitoring-subscription"
    topic: "processing-errors"
    ack_deadline: 60
    message_retention: 2592000  # 30 días
    labels:
      service: "monitoring"
      type: "pull"

# Esquemas de mensajes
message_schemas:
  shipment_packages_ready:
    type: "object"
    properties:
      processing_uuid:
        type: "string"
        description: "UUID único del procesamiento generado por division_service"
      original_file:
        type: "string" 
        description: "Nombre del archivo JSON original"
      packages:
        type: "array"
        description: "Lista de URIs de paquetes en bucket json-a-procesar"
        items:
          type: "string"
      total_shipments:
        type: "integer"
        description: "Total de envíos procesados"
      division_metadata:
        type: "object"
        description: "Metadatos adicionales del procesamiento de división"
    required:
      - processing_uuid
      - original_file
      - packages
      - total_shipments

  email_notification:
    type: "object"
    properties:
      processing_uuid:
        type: "string"
      email_type:
        type: "string"
        enum: ["completion", "error"]
      signed_urls:
        type: "array"
        items:
          type: "string"
      processing_summary:
        type: "object"
      recipient_email:
        type: "string"
    required:
      - processing_uuid
      - email_type
